In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df1 = df.copy()

In [4]:
df1.head()

Timestamp   ID   Age?  Gender  \
0   2/9/2018 21:05:31  101  30-40    Male   
1   2/9/2018 21:35:41  102  20-30    Male   
2  2/12/2018 12:25:41  103  20-30    Male   
3  2/12/2018 12:26:00  104  20-30    Male   
4  2/12/2018 12:26:16  105  20-30  Female   

                                    Preferred Genres  \
0        Comedy, Action,  Romantic, Animation, Drama   
1                              Comedy, Action, Drama   
2  Comedy, Action, Sci-Fi & Fantasy, Romantic, An...   
3                Action, Sci-Fi & Fantasy, Animation   
4                 Comedy, Sci-Fi & Fantasy, Romantic   

   Rating [Rogue One/Star Wars]  Rating [Fight Club]  \
0                           NaN                  5.0   
1                           5.0                  NaN   
2                           5.0                  5.0   
3                           4.0                  5.0   
4                           NaN                  NaN   

   Rating [The Lord of the Rings]  Rating [Trolls]  Rating [Despicable Me]  \
0                             5.0              NaN                     NaN   
1                             5.0              4.0                     5.0   
2                             5.0              NaN                     2.0   
3                             4.0              NaN                     5.0   
4                             4.0              NaN                     4.0   

          ...          Rating [The hangover]  Rating [Captain America]  \
0         ...                            3.0                       NaN   
1         ...                            4.0                       4.0   
2         ...                            2.0                       5.0   
3         ...                            NaN                       4.0   
4         ...                            NaN                       5.0   

   Rating [The big Lebowski]  Rating [Almost famous]  \
0                        NaN                     NaN   
1                        3.0                     3.0   
2                        5.0                     5.0   
3                        NaN                     NaN   
4                        NaN                     NaN   

   Rating [The hunger games]  Rating [Pulp Fiction]  Rating [Sing ]  \
0                        2.0                    NaN             NaN   
1                        3.0                    3.0             3.0   
2                        2.0                    5.0             NaN   
3                        NaN                    NaN             3.0   
4                        NaN                    NaN             NaN   

   Rating [500 days of Summer]  Rating [Twilight]  Rating [Lala Land]  
0                          5.0                5.0                 5.0  
1                          5.0                5.0                 5.0  
2                          NaN                3.0                 5.0  
3                          4.0                2.0                 3.0  
4                          NaN                3.0                 5.0  

[5 rows x 21 columns]

In [5]:
n_users = df1.ID.unique().shape[0]
n_movies = 16
print n_users

97


In [6]:
del df1['Timestamp']
del df1['Age?']
del df1['Gender']
del df1['Preferred Genres']
del df1['ID']



In [7]:
df1.fillna(0, inplace = True)
df1.head()

Rating [Rogue One/Star Wars]  Rating [Fight Club]  \
0                           0.0                  5.0   
1                           5.0                  0.0   
2                           5.0                  5.0   
3                           4.0                  5.0   
4                           0.0                  0.0   

   Rating [The Lord of the Rings]  Rating [Trolls]  Rating [Despicable Me]  \
0                             5.0              0.0                     0.0   
1                             5.0              4.0                     5.0   
2                             5.0              0.0                     2.0   
3                             4.0              0.0                     5.0   
4                             4.0              0.0                     4.0   

   Rating [Kubo]  Rating [The hangover]  Rating [Captain America]  \
0            0.0                    3.0                       0.0   
1            4.0                    4.0                       4.0   
2            3.0                    2.0                       5.0   
3            0.0                    0.0                       4.0   
4            0.0                    0.0                       5.0   

   Rating [The big Lebowski]  Rating [Almost famous]  \
0                        0.0                     0.0   
1                        3.0                     3.0   
2                        5.0                     5.0   
3                        0.0                     0.0   
4                        0.0                     0.0   

   Rating [The hunger games]  Rating [Pulp Fiction]  Rating [Sing ]  \
0                        2.0                    0.0             0.0   
1                        3.0                    3.0             3.0   
2                        2.0                    5.0             0.0   
3                        0.0                    0.0             3.0   
4                        0.0                    0.0             0.0   

   Rating [500 days of Summer]  Rating [Twilight]  Rating [Lala Land]  
0                          5.0                5.0                 5.0  
1                          5.0                5.0                 5.0  
2                          0.0                3.0                 5.0  
3                          4.0                2.0                 3.0  
4                          0.0                3.0                 5.0

In [8]:
df1.head()

Rating [Rogue One/Star Wars]  Rating [Fight Club]  \
0                           0.0                  5.0   
1                           5.0                  0.0   
2                           5.0                  5.0   
3                           4.0                  5.0   
4                           0.0                  0.0   

   Rating [The Lord of the Rings]  Rating [Trolls]  Rating [Despicable Me]  \
0                             5.0              0.0                     0.0   
1                             5.0              4.0                     5.0   
2                             5.0              0.0                     2.0   
3                             4.0              0.0                     5.0   
4                             4.0              0.0                     4.0   

   Rating [Kubo]  Rating [The hangover]  Rating [Captain America]  \
0            0.0                    3.0                       0.0   
1            4.0                    4.0                       4.0   
2            3.0                    2.0                       5.0   
3            0.0                    0.0                       4.0   
4            0.0                    0.0                       5.0   

   Rating [The big Lebowski]  Rating [Almost famous]  \
0                        0.0                     0.0   
1                        3.0                     3.0   
2                        5.0                     5.0   
3                        0.0                     0.0   
4                        0.0                     0.0   

   Rating [The hunger games]  Rating [Pulp Fiction]  Rating [Sing ]  \
0                        2.0                    0.0             0.0   
1                        3.0                    3.0             3.0   
2                        2.0                    5.0             0.0   
3                        0.0                    0.0             3.0   
4                        0.0                    0.0             0.0   

   Rating [500 days of Summer]  Rating [Twilight]  Rating [Lala Land]  
0                          5.0                5.0                 5.0  
1                          5.0                5.0                 5.0  
2                          0.0                3.0                 5.0  
3                          4.0                2.0                 3.0  
4                          0.0                3.0                 5.0

In [9]:
ratings = df1.as_matrix()
print ratings

[[ 0.  5.  5. ...,  5.  5.  5.]
 [ 5.  0.  5. ...,  5.  5.  5.]
 [ 5.  5.  5. ...,  0.  3.  5.]
 ..., 
 [ 5.  3.  5. ...,  3.  5.  5.]
 [ 0.  5.  0. ...,  3.  2.  3.]
 [ 0.  5.  5. ...,  3.  5.  2.]]


In [10]:
def similarity_calculation(ratings):
    sim = ratings.T.dot(ratings) 
    norms = np.array([np.sqrt(np.diagonal(sim))])
    return (sim / norms / norms.T)

In [11]:
item_similarity = similarity_calculation(ratings)


In [12]:
test = pd.read_csv('test.csv')

In [13]:
test.head()

ID   Age?  Gender                    Preferred Genres  \
0   1  30-40  Female       Comedy, Independent, Romantic   
1   2  20-30  Female  Comedy, Sci-Fi & Fantasy, Romantic   
2   3  20-30    Male    Comedy, Action, Sci-Fi & Fantasy   
3   4  20-30    Male                              Action   
4   5  20-30    Male    Comedy, Action, Sci-Fi & Fantasy   

   Rating [Rogue One/Star Wars]  Rating [Fight Club]  \
0                           NaN                  5.0   
1                           NaN                  NaN   
2                           4.0                  5.0   
3                           3.0                  3.0   
4                           NaN                  5.0   

   Rating [The Lord of the Rings]  Rating [Trolls]  Rating [Despicable Me]  \
0                             3.0              NaN                     NaN   
1                             NaN              NaN                     NaN   
2                             5.0              4.0                     NaN   
3                             5.0              3.0                     NaN   
4                             3.0              NaN                     NaN   

   Rating [Kubo]  Rating [The hangover]  Rating [Captain America]  \
0            NaN                    2.0                       NaN   
1            NaN                    NaN                       NaN   
2            3.0                    2.0                       4.0   
3            NaN                    5.0                       5.0   
4            NaN                    5.0                       3.0   

   Rating [The big Lebowski]  Rating [Almost famous]  \
0                        4.0                     4.0   
1                        NaN                     NaN   
2                        5.0                     5.0   
3                        NaN                     NaN   
4                        NaN                     NaN   

   Rating [The hunger games]  Rating [Pulp Fiction]  Rating [Sing ]  \
0                        4.0                    4.0             4.0   
1                        NaN                    NaN             NaN   
2                        3.0                    5.0             4.0   
3                        3.0                    NaN             NaN   
4                        NaN                    5.0             NaN   

   Rating [500 days of Summer]  Rating [Twilight]  Rating [Lala Land]  
0                          3.0                NaN                 5.0  
1                          3.0                1.0                 1.0  
2                          4.0                1.0                 3.0  
3                          4.0                1.0                 NaN  
4                          NaN                1.0                 1.0

In [14]:
test1 = test.copy()

In [15]:
del test1['Age?']
del test1['Gender']
del test1['Preferred Genres']
del test1['ID']



In [16]:
test1.fillna(0, inplace = True)
test1.head()

Rating [Rogue One/Star Wars]  Rating [Fight Club]  \
0                           0.0                  5.0   
1                           0.0                  0.0   
2                           4.0                  5.0   
3                           3.0                  3.0   
4                           0.0                  5.0   

   Rating [The Lord of the Rings]  Rating [Trolls]  Rating [Despicable Me]  \
0                             3.0              0.0                     0.0   
1                             0.0              0.0                     0.0   
2                             5.0              4.0                     0.0   
3                             5.0              3.0                     0.0   
4                             3.0              0.0                     0.0   

   Rating [Kubo]  Rating [The hangover]  Rating [Captain America]  \
0            0.0                    2.0                       0.0   
1            0.0                    0.0                       0.0   
2            3.0                    2.0                       4.0   
3            0.0                    5.0                       5.0   
4            0.0                    5.0                       3.0   

   Rating [The big Lebowski]  Rating [Almost famous]  \
0                        4.0                     4.0   
1                        0.0                     0.0   
2                        5.0                     5.0   
3                        0.0                     0.0   
4                        0.0                     0.0   

   Rating [The hunger games]  Rating [Pulp Fiction]  Rating [Sing ]  \
0                        4.0                    4.0             4.0   
1                        0.0                    0.0             0.0   
2                        3.0                    5.0             4.0   
3                        3.0                    0.0             0.0   
4                        0.0                    5.0             0.0   

   Rating [500 days of Summer]  Rating [Twilight]  Rating [Lala Land]  
0                          3.0                0.0                 5.0  
1                          3.0                1.0                 1.0  
2                          4.0                1.0                 3.0  
3                          4.0                1.0                 0.0  
4                          0.0                1.0                 1.0

In [17]:

ratings_test = test1.as_matrix()



print ratings_test

[[ 0.  5.  3.  0.  0.  0.  2.  0.  4.  4.  4.  4.  4.  3.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  1.  1.]
 [ 4.  5.  5.  4.  0.  3.  2.  4.  5.  5.  3.  5.  4.  4.  1.  3.]
 [ 3.  3.  5.  3.  0.  0.  5.  5.  0.  0.  3.  0.  0.  4.  1.  0.]
 [ 0.  5.  3.  0.  0.  0.  5.  3.  0.  0.  0.  5.  0.  0.  1.  1.]
 [ 4.  3.  5.  4.  0.  4.  3.  4.  0.  0.  4.  3.  3.  4.  1.  0.]
 [ 5.  0.  4.  0.  0.  4.  2.  0.  0.  0.  0.  0.  3.  0.  5.  1.]
 [ 5.  0.  4.  3.  0.  5.  0.  2.  0.  0.  1.  0.  3.  0.  5.  5.]
 [ 0.  5.  5.  0.  0.  3.  4.  4.  0.  0.  3.  5.  3.  5.  2.  4.]
 [ 3.  0.  4.  4.  0.  0.  0.  4.  0.  0.  3.  0.  0.  0.  4.  0.]
 [ 0.  5.  4.  0.  0.  0.  5.  4.  0.  0.  1.  5.  0.  3.  1.  0.]
 [ 0.  5.  4.  0.  0.  0.  2.  3.  0.  3.  4.  5.  0.  2.  1.  1.]
 [ 5.  4.  5.  4.  0.  0.  3.  0.  5.  0.  0.  4.  0.  0.  0.  0.]
 [ 0.  0.  4.  0.  0.  0.  3.  4.  0.  0.  0.  4.  0.  4.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  5.  5.  0.  0.  0.  0.  0.  0.  5. 

In [19]:
def predict_topk(ratings, similarity, k=3):
    pred = np.zeros(ratings.shape)
    for j in xrange(ratings.shape[1]):
        top_k_items = [np.argsort(similarity[:,j])[:-k-1:-1]]
        for i in xrange(ratings.shape[0]):
            pred[i, j] = similarity[j, :][top_k_items].dot(ratings[i, :][top_k_items].T) 
            pred[i, j] /= np.sum(np.abs(similarity[j, :][top_k_items]))        
    
    return pred

In [20]:
pre = predict_topk(ratings_test, item_similarity, k = 3)


In [21]:

print pre

[[ 0.90859898  3.48490145  1.11882689  1.15828598  0.92794911  2.25823941
   1.6721335   0.62860474  4.          2.86103     1.58479634  4.00900746
   1.7666141   1.28505683  0.          1.95561035]
 [ 0.          0.          0.          0.27911414  0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.57449762  0.38184362  0.69258889]
 [ 4.30286633  4.10799637  3.12324018  3.45222909  2.8323928   3.83541089
   3.5661391   2.09486649  5.          4.7152575   2.38687386  5.
   3.7021002   3.13167764  1.60894858  1.47483303]
 [ 4.19243915  4.217764    3.43787235  1.57305725  3.15384554  0.          5.
   3.40433904  0.          0.8542275   2.68644301  2.3860585   0.78134002
   2.8494707   1.91572482  0.30146682]
 [ 1.78865873  4.37690508  2.06272341  0.27911414  1.89230732  1.35425519
   3.74342905  2.67120817  1.26076402  0.          0.89870746  4.41024097
   0.          0.28944079  1.30217234  0.69258889]
 [ 4.30286633  3.62309492  3.12324018

In [22]:
df_revised = pd.DataFrame(data = pre, columns = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p'])

In [23]:
df_revised.head()

a         b         c         d         e         f         g  \
0  0.908599  3.484901  1.118827  1.158286  0.927949  2.258239  1.672133   
1  0.000000  0.000000  0.000000  0.279114  0.000000  0.000000  0.000000   
2  4.302866  4.107996  3.123240  3.452229  2.832393  3.835411  3.566139   
3  4.192439  4.217764  3.437872  1.573057  3.153846  0.000000  5.000000   
4  1.788659  4.376905  2.062723  0.279114  1.892307  1.354255  3.743429   

          h         i         j         k         l         m         n  \
0  0.628605  4.000000  2.861030  1.584796  4.009007  1.766614  1.285057   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.574498   
2  2.094866  5.000000  4.715258  2.386874  5.000000  3.702100  3.131678   
3  3.404339  0.000000  0.854227  2.686443  2.386058  0.781340  2.849471   
4  2.671208  1.260764  0.000000  0.898707  4.410241  0.000000  0.289441   

          o         p  
0  0.000000  1.955610  
1  0.381844  0.692589  
2  1.608949  1.474833  
3  1.915725  0.301467  
4  1.302172  0.692589

In [24]:
result = pd.DataFrame({'ID': test['ID'], 'Rating [Despicable Me]':df_revised['e']})
result = result[['ID', 'Rating [Despicable Me]']]
result.set_index('ID', inplace=True)


In [25]:
result.head()

Rating [Despicable Me]
ID                        
1                 0.927949
2                 0.000000
3                 2.832393
4                 3.153846
5                 1.892307

In [26]:
result.to_csv('rating.csv')